name: biyi_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0-alpha+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audioplayers: ^0.19.1
  bot_toast: ^4.0.1
  dart_vlc: ^0.1.4
  dio: ^4.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  hotkey_manager:
    git:
      url: https://github.com/leanflutter/hotkey_manager.git
      ref: main
  package_info_plus: ^1.0.4
  photo_view: ^0.12.0
  screen_text_extractor:
    git:
      url: https://github.com/leanflutter/screen_text_extractor.git
      ref: main
  sticky_headers: ^0.1.8
  tray_manager:
    git:
      url: https://github.com/leanflutter/tray_manager.git
      ref: main
  uni_links: ^0.5.1
  uni_links_macos:
    git:
      url: https://github.com/biyidev/dart_pkgs.git
      ref: master
      path: packages/uni_links_macos
  uni_ocr:
    git:
      url: https://github.com/biyidev/uni_ocr.git
      ref: master
      path: packages/uni_ocr
  uni_ocr_client:
    git:
      url: https://github.com/biyidev/uni_ocr.git
      ref: master
      path: packages/uni_ocr_client
  uni_translate:
    git:
      url: https://github.com/biyidev/uni_translate.git
      ref: master
      path: packages/uni_translate
  url_launcher: ^6.0.6
  uuid: ^3.0.4
  window_manager:
    git:
      url: https://github.com/leanflutter/window_manager.git
      ref: main
  yaml_localizations: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
#   hotkey_manager:
#     path: ../../leanflutter/hotkey_manager
#   screen_text_extractor:
#     path: ../../leanflutter/screen_text_extractor
#   tray_manager:
#     path: ../../leanflutter/tray_manager
  uni_ocr:
    path: ../uni_ocr/packages/uni_ocr
  uni_ocr_client:
    path: ../uni_ocr/packages/uni_ocr_client
  uni_translate:
    path: ../uni_translate/packages/uni_translate
  uni_translate_client:
    path: ../uni_translate/packages/uni_translate_client
#   window_manager:
#     path: ../../leanflutter/window_manager

flutter:
  uses-material-design: true

  assets:
    - assets/environments/
    - assets/images/
    - assets/images/flag_icons/
    - assets/images/ocr_engine_icons/
    - assets/images/translation_engine_icons/
    - assets/languages/
    - packages/hotkey_manager/js/
    - packages/screen_text_extractor/js/
    - packages/window_manager/js/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
